/*
 * This file is generated by jOOQ.
 */
package com.model.mixer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        userName;
    private String        password;
    private String        nickName;
    private Integer       roleId;
    private String        avatar;
    private String        phone;
    private Integer       sex;
    private String        idcard;
    private String        address;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private String        deleteStatus;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.userName = value.userName;
        this.password = value.password;
        this.nickName = value.nickName;
        this.roleId = value.roleId;
        this.avatar = value.avatar;
        this.phone = value.phone;
        this.sex = value.sex;
        this.idcard = value.idcard;
        this.address = value.address;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleteStatus = value.deleteStatus;
    }

    public User(
        Integer       id,
        String        userName,
        String        password,
        String        nickName,
        Integer       roleId,
        String        avatar,
        String        phone,
        Integer       sex,
        String        idcard,
        String        address,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        String        deleteStatus
    ) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.nickName = nickName;
        this.roleId = roleId;
        this.avatar = avatar;
        this.phone = phone;
        this.sex = sex;
        this.idcard = idcard;
        this.address = address;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleteStatus = deleteStatus;
    }

    /**
     * Getter for <code>model_mixer.user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>model_mixer.user.id</code>.
     */
    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.user_name</code>. 用户名
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>model_mixer.user.user_name</code>. 用户名
     */
    public User setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.password</code>. 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>model_mixer.user.password</code>. 密码
     */
    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.nick_name</code>. 昵称
     */
    public String getNickName() {
        return this.nickName;
    }

    /**
     * Setter for <code>model_mixer.user.nick_name</code>. 昵称
     */
    public User setNickName(String nickName) {
        this.nickName = nickName;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>model_mixer.user.role_id</code>. 角色ID
     */
    public User setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.avatar</code>.
     */
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * Setter for <code>model_mixer.user.avatar</code>.
     */
    public User setAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>model_mixer.user.phone</code>.
     */
    public User setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.sex</code>. true:男，false：女
     */
    public Integer getSex() {
        return this.sex;
    }

    /**
     * Setter for <code>model_mixer.user.sex</code>. true:男，false：女
     */
    public User setSex(Integer sex) {
        this.sex = sex;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.idcard</code>.
     */
    public String getIdcard() {
        return this.idcard;
    }

    /**
     * Setter for <code>model_mixer.user.idcard</code>.
     */
    public User setIdcard(String idcard) {
        this.idcard = idcard;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>model_mixer.user.address</code>.
     */
    public User setAddress(String address) {
        this.address = address;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>model_mixer.user.create_time</code>. 创建时间
     */
    public User setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>model_mixer.user.update_time</code>. 修改时间
     */
    public User setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * Getter for <code>model_mixer.user.delete_status</code>. 是否有效  1有效  2无效
     */
    public String getDeleteStatus() {
        return this.deleteStatus;
    }

    /**
     * Setter for <code>model_mixer.user.delete_status</code>. 是否有效  1有效  2无效
     */
    public User setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!userName.equals(other.userName))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (nickName == null) {
            if (other.nickName != null)
                return false;
        }
        else if (!nickName.equals(other.nickName))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        if (avatar == null) {
            if (other.avatar != null)
                return false;
        }
        else if (!avatar.equals(other.avatar))
            return false;
        if (phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!phone.equals(other.phone))
            return false;
        if (sex == null) {
            if (other.sex != null)
                return false;
        }
        else if (!sex.equals(other.sex))
            return false;
        if (idcard == null) {
            if (other.idcard != null)
                return false;
        }
        else if (!idcard.equals(other.idcard))
            return false;
        if (address == null) {
            if (other.address != null)
                return false;
        }
        else if (!address.equals(other.address))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!updateTime.equals(other.updateTime))
            return false;
        if (deleteStatus == null) {
            if (other.deleteStatus != null)
                return false;
        }
        else if (!deleteStatus.equals(other.deleteStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.nickName == null) ? 0 : this.nickName.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.avatar == null) ? 0 : this.avatar.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.sex == null) ? 0 : this.sex.hashCode());
        result = prime * result + ((this.idcard == null) ? 0 : this.idcard.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleteStatus == null) ? 0 : this.deleteStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(nickName);
        sb.append(", ").append(roleId);
        sb.append(", ").append(avatar);
        sb.append(", ").append(phone);
        sb.append(", ").append(sex);
        sb.append(", ").append(idcard);
        sb.append(", ").append(address);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleteStatus);

        sb.append(")");
        return sb.toString();
    }
}
