server:
  port: 9202
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  # ############################################# MySQL 配置 ############################################
  datasource:
    url: jdbc:mysql://47.97.123.182:3306/model_mixer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 8662291069wzc
    driver-class-name: com.mysql.cj.jdbc.Driver

# ############################################# Mysql 配置 ############################################
