/*
 * This file is generated by jOOQ.
 */
package com.model.mixer.jooq;


import com.model.mixer.jooq.tables.User;


/**
 * Convenience access to all tables in model_mixer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户表
     */
    public static final User USER = User.USER;
}
